//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDashboardApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentDashboardApp.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        internal static string BtnAddStudent {
            get {
                return ResourceManager.GetString("BtnAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string BtnAttendance {
            get {
                return ResourceManager.GetString("BtnAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database  Connection.
        /// </summary>
        internal static string BtnDatabase {
            get {
                return ResourceManager.GetString("BtnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Student.
        /// </summary>
        internal static string BtnEditStudent {
            get {
                return ResourceManager.GetString("BtnEditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Student.
        /// </summary>
        internal static string BtnFindStudent {
            get {
                return ResourceManager.GetString("BtnFindStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List by class or year.
        /// </summary>
        internal static string BtnListClassOrYear {
            get {
                return ResourceManager.GetString("BtnListClassOrYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Logs.
        /// </summary>
        internal static string BtnLogs {
            get {
                return ResourceManager.GetString("BtnLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string BtnOverview {
            get {
                return ResourceManager.GetString("BtnOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Student Score.
        /// </summary>
        internal static string BtnStudentScore {
            get {
                return ResourceManager.GetString("BtnStudentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Conection.
        /// </summary>
        internal static string BtnTest {
            get {
                return ResourceManager.GetString("BtnTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Students.
        /// </summary>
        internal static string BtnTopStudents {
            get {
                return ResourceManager.GetString("BtnTopStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transript.
        /// </summary>
        internal static string BtnTranscript {
            get {
                return ResourceManager.GetString("BtnTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Students by Faculty.
        /// </summary>
        internal static string Chart_StudentsPerFaculty {
            get {
                return ResourceManager.GetString("Chart_StudentsPerFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students per Academic Year Chart.
        /// </summary>
        internal static string Chart_StudentsPerYear {
            get {
                return ResourceManager.GetString("Chart_StudentsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Students.
        /// </summary>
        internal static string Chart_Top5Students {
            get {
                return ResourceManager.GetString("Chart_Top5Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassRibbon {
            get {
                return ResourceManager.GetString("ClassRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majors.
        /// </summary>
        internal static string Lbl_MajorCount {
            get {
                return ResourceManager.GetString("Lbl_MajorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Lbl_StudentCount {
            get {
                return ResourceManager.GetString("Lbl_StudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        internal static string Lbl_TeacherCount {
            get {
                return ResourceManager.GetString("Lbl_TeacherCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majors.
        /// </summary>
        internal static string Majors {
            get {
                return ResourceManager.GetString("Majors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while resetting application.
        /// </summary>
        internal static string Msg_AppResetError {
            get {
                return ResourceManager.GetString("Msg_AppResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been reset to default!.
        /// </summary>
        internal static string Msg_AppResetSuccess {
            get {
                return ResourceManager.GetString("Msg_AppResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        internal static string MsgSaved {
            get {
                return ResourceManager.GetString("MsgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student .
        /// </summary>
        internal static string StudentRibbon {
            get {
                return ResourceManager.GetString("StudentRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemRibbon {
            get {
                return ResourceManager.GetString("SystemRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        internal static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameter.
        /// </summary>
        internal static string TxtSystemParameter {
            get {
                return ResourceManager.GetString("TxtSystemParameter", resourceCulture);
            }
        }
    }
}
